#ifndef VERSION_H
#define VERSION_H

#define DEVICE_SW_BUILD_NUM "20260412185454"
#define DEVICE_SW_VERSION_NUM "1.2.0"
#define DEVICE_SW_VERSION DEVICE_SW_VERSION_NUM " build " DEVICE_SW_BUILD_NUM

#endif // VERSION_H
